API_REST/HotelCliente/Models/JQueryDataTableParamModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HotelCliente.Models
{
    public class JQueryDataTableParamModel
    {
        public int draw { get; set; }
        public int start { get; set; }
        public int length { get; set; }
        public Dictionary<string, string> search { get; set; }
        public List<JQDTColumnOrder/*Dictionary<string, string>*/> order { get; set; }
        public List<JQDTColumn/*Dictionary<string, string>*/> columns { get; set; }

    }

    public enum JQDTColumnOrderDirection
    {
        asc, desc
    }

    public class JQDTColumnOrder
    {
        public int column { get; set; }
        public JQDTColumnOrderDirection dir { get; set; }
    }

    public class JQDTColumnSearch
    {
        public string value { get; set; }
        public string regex { get; set; }
    }

    public class JQDTColumn
    {
        public string data { get; set; }
        public string name { get; set; }
        public bool searchable { get; set; }
        public bool orderable { get; set; }
        public JQDTColumnSearch search { get; set; }
    }
}

API_REST/HotelCliente/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelCliente.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

API_REST/HotelCliente/Controllers/ReservaController.cs
using DataTables.Mvc;
using HotelCliente.ConsumeApi;
using HotelCliente.Entidades;
using HotelCliente.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelCliente.Controllers
{
    public class ReservaController : Controller
    {
        // GET: Reserva
        public ActionResult Index()
        {


            return View();
        }

        public ActionResult Details(int id)
        {
            ApiRequest obj = new ApiRequest();

            var result = obj.GetReservaId(id);

            return View();
        }

        public ActionResult Crear()
        {
            ApiRequest obj = new ApiRequest();

            var lt = obj.GetSede();
            List<string> FormaPago = new List<string>();
            FormaPago.Add("Efectivo");
            FormaPago.Add("Tarjeta Credito");
            FormaPago.Add("Cheque");

            ViewBag.FormaPago = new SelectList(FormaPago, "value");

            ViewBag.TipoSede = new SelectList(lt, "Id", "Nombre");

            return View();
        }

        [HttpPost]
        public ActionResult Crear(FormCollection collection)
        {
            ApiRequest obj = new ApiRequest();
            var Reserva = collection;
            System.Threading.Thread.CurrentThread.CurrentCulture = new CultureInfo("en-CA");

            var NewReserva = new Reserva()
            {
                Cantidad_personas = int.Parse(collection["Cantidad_personas"].ToString()),
                Cedula_Cliente = int.Parse(collection["Cedula_Cliente"].ToString()),
                Fecha = DateTime.Parse(collection["Fecha"].ToString()),
                Cod_Sede = int.Parse(collection["Id"].ToString()),
                Cod_Pago = collection["value"].ToString()
            };

            obj.PostReserva(NewReserva);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult consultaReserva(JQueryDataTableParamModel param)
        {
            ApiRequest obj = new ApiRequest();

            var result = obj.GetReserva();


            var jsonResult = Json(new
            {
                draw = param.draw,
                data = result,
                recordsTotal = result.Count,
                recordsFiltered = result.Count
            }, JsonRequestBehavior.AllowGet);

            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }
    }
}

API_REST/HotelCliente/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

API_REST/HotelCliente/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

API_REST/HotelCliente/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

API_REST/HotelCliente/Views/Reserva/Crear.cshtml
@model HotelCliente.Entidades.Reserva


@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

<div class="well well-lg">
    @if (Session["Message"] != null)
    {
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" type="button" data-dismiss="alert">×</button>
            @Session["Message"].ToString()
        </div>
        Session.Remove("Message");
    }


    <div class="container">
        @using (Html.BeginForm("Crear", "Reserva", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()

            <div id="home" class="tab-pane fade in active">
                <div class="panel-body">
                    <div class="col-md-12">
                        <div class="row col-md-12">
                            <div class="row col-md-12" style="text-align:center; margin-bottom:30px">
                                <p><h3 class="h2">Creación Reserva</h3></p>
                            </div>

                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Cedula_Cliente, new { @class = "h5 col-md-4 control-label" })

                                @Html.TextBoxFor(model => model.Cedula_Cliente, new { @class = "col-md-8 control-label-data" })
                                @Html.ValidationMessageFor(model => model.Cedula_Cliente, "", new { @class = "text-danger" })
                            </div>

                        </div>
                        <div class="row col-md-12">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Cantidad_personas, new { @class = "h5 col-md-4 control-label" })

                                @Html.TextBoxFor(model => model.Cantidad_personas, new { @class = "col-md-8 control-label-data" })
                                @Html.ValidationMessageFor(model => model.Cantidad_personas, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row col-md-12">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Fecha, new { @class = "h5 col-md-4 control-label" })

                                @Html.TextBoxFor(model => model.Fecha, "{0:MM/dd/yy}", new { @class = "col-md-8 date-picker" })
                                @Html.ValidationMessageFor(model => model.Fecha, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="row col-md-12">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Cod_Pago, new { @class = "h5 col-md-4 control-label" })

                                @Html.DropDownList("value", (IEnumerable<SelectListItem>)ViewBag.FormaPago, "Seleccione", new { @class = "col-md-8 control-label-data", @title = "Seleccione Forma de Pago" })
                                @Html.ValidationMessageFor(model => model.Cod_Sede)
                            </div>
                        </div>
                        <div class="row col-md-12">
                            <div class="col-md-6">
                                @Html.LabelFor(model => model.Cod_Sede, new { @class = "h5 col-md-4 control-label" })

                                @Html.DropDownList("Id", (IEnumerable<SelectListItem>)ViewBag.TipoSede, "Seleccione", new { @class = "col-md-8 control-label-data", @title = "Seleccione Sede" })
                                @Html.ValidationMessageFor(model => model.Cod_Sede)
                            </div>
                        </div>

                    </div>

                </div>
                <div class="panel-footer">
                    <button type="submit" class="btn btn-primary" id="btnSave">
                        <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>&nbsp;Guardar
                    </button>
                    <a class="btn btn-default" role="button" href="@Url.Action("Index", "Categoria")">
                        <span class='glyphicon glyphicon-arrow-left' aria-hidden='true'></span> &nbsp;Cancelar
                    </a>
                </div>
            </div>

        }
    </div>
</div>

API_REST/HotelCliente/Views/Reserva/Details.cshtml
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

API_REST/HotelCliente/Views/Reserva/Index.cshtml
@model IEnumerable<HotelCliente.Entidades.Reserva>

@{
    ViewBag.Title = "Index";
}

<h2>Reservaciones:</h2>

<div>

    @*<button class="btn btn-primary" href="@Url.Action("Crear", "Reserva")">Crear Reserva</button>*@
    <a class="btn btn-default" role="button" href="@Url.Action("Crear")">
        <span class='glyphicon glyphicon-arrow-right' aria-hidden='true'></span> &nbsp;Nueva Reservación
    </a>
    <br />
    <br />

    <table id="consultaReserva" class="table-striped table-bordered" style="width:100%;">
    </table>

</div>

@section Scripts {
    <script type="text/javascript">


        $(document).ready(function () {




            $('#consultaReserva').DataTable({
                 "bSort": false,
                        "dom": 'lfrtip',

                        "serverSide": true,

                        "processing": false,
                        "rowHeight": 'auto',
                        "scrollX": true,
                        "responsive": false,

                        "ajax": {
                            "url":
                                "@Url.Action("consultaReserva")",
                            "type": "POST",

                        },
                        "columns": [


                            {
                                "title": "#Reserva",
                                "data": "Cod_Reserva",
                                "searchable": true,
                                "visible": true,
                                className: 'text-center',
                            },

                            {
                                "title": "Sede",
                                "data": "NombreSede",
                                "searchable": true,
                                "visible": true,
                                className: 'text-center',
                            },

                            {
                                "title": "Fecha",
                                "data": "FechaMuestra",
                                "searchable": true,
                                "visible": true,

                                className: 'Item',
                            },

                            {
                                "title": "Cedula Cliente",
                                "data": "Cedula_Cliente",
                                "searchable": true,
                                "visible": true,
                                className: 'text-center',
                            },


                            {
                                "title": "Forma de Pago",
                                "data": "Cod_Pago",
                                "searchable": true,
                                "visible": true,
                                className: 'text-center',
                            },

                            {
                                "title": "#Personas",
                                "data": "Cantidad_personas",
                                "searchable": true,
                                "visible": true,
                                className: 'text-center',
                            },

                        ],
                        "lengthMenu": [[10, 25, 50, 100], [10, 25, 50, 100]],
            });

        });

    </script>
}

API_REST/HotelCliente/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@
    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/bundledatatables")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datatables")
    @RenderSection("scripts", required: false)
</body>
</html>